site_name: MBfR-Lab
repo_url: https://github.com/Eulogy320/MBfR-Lab
site_description: Repositorio de protocolos del MBfR-Lab, Fondecyt Nº 11191026.
nav:
- Inicio: 'index.md'
- Preparación de Medios de Cultivo: 'Medios_de_cultivo.md'
- Análisis de metagenómica: 'metagenomica_pretratamiento.md'
- Determinación parámetros fisico-químicos
   Cuantificacion de Amonio: 'Cuantificación amonio.md'
   Cuantificación de Nitrito: 'Cuantificación Nitrito.md'
   Cuantificación de DQO: 'Demanda Quḿica Oxígeno ( COD - Method 800 Hach).md'
theme: readthedocs
